name: Deploy

on:
  push:
    branches:
      - master   # or main — make sure it matches your real branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH (hard reset)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd "${{ secrets.WORK_DIR }}"

            echo "Force syncing with origin/${{ secrets.MAIN_BRANCH }}..."
            git fetch origin "${{ secrets.MAIN_BRANCH }}"
            git reset --hard "origin/${{ secrets.MAIN_BRANCH }}"
            git clean -fdx

            echo "Setting up virtual environment..."
            if [ -d .venv ]; then
              source .venv/bin/activate
            else
              python3 -m venv .venv
              source .venv/bin/activate
            fi

            pip install --upgrade pip
            [ -f requirements.txt ] && pip install -r requirements.txt

            echo "Restarting echoes-website service..."
            sudo systemctl restart echoes-website
            sudo systemctl status echoes-website --no-pager --lines=5 || true
